/**
 * The executable VS Code spawns for a DevHub terminal.
 *
 * DevHub's terminals live in a tmux server DevHub owns, and the argv that
 * attaches to one is DevHub's to compute — the session name, the socket and
 * the marker protocol belong to the terminal runtime and must not be spelled
 * anywhere else. So the integrated terminal does not run a shell: it runs this
 * launcher, which asks DevHub over the control socket (the `terminal-profile`
 * request) and runs the answer.
 *
 * Why a file on disk rather than an extension-contributed profile. A
 * contributed profile is only a profile once the extension host has registered
 * the manifest *and* `TerminalProfileService` has refreshed its contributed
 * list — a throttled refresh that does a pty-host round trip first. A terminal
 * created on window load (the panel is visible, there are no persistent
 * sessions to restore, so `TerminalViewPane` creates one immediately) happens
 * before all of that and silently gets the OS shell: a plain zsh outside tmux.
 * A profile whose `path` is a real executable has no such window. It is in the
 * settings before the first frame, and no extension host has to be alive for a
 * terminal to be a DevHub terminal.
 *
 * Why the script is *generated* on every startup, like the `devhub` CLI's
 * launcher in `../cli/install.ts`: it records the two absolute facts a launcher
 * cannot discover on its own — which binary runs it as Node (the app's own
 * Electron, since a system Node is exactly the thing in doubt) and which
 * control socket this DevHub is listening on. Regenerating means a moved or
 * updated app is never running yesterday's paths, and a second DevHub on
 * another profile never talks to the first one's socket.
 *
 * The socket is written *into* the script rather than read from the
 * environment because `DEVHUB_*` is a family a terminal is not supposed to
 * inherit — see `../shell/loginEnvironment.ts`. Nothing has to reach the
 * workbench through the environment either: the profile that names this file
 * names it by its absolute path, which `../workbenchDefaults.ts` writes into
 * the settings file the workbench starts with.
 *
 * That is also where `terminal.integrated.enablePersistentSessions` is turned
 * off, and the reasoning is the same one. That setting exists to solve a problem DevHub does not have:
 * upstream persists a terminal's tab and replays its scrollback because closing
 * the window would otherwise kill the shell. Here the shell is in tmux and
 * outlives everything, so the tab restored on the next launch is a second,
 * empty client for a session that is already running. Opening a terminal
 * reattaches to the same session with its history intact, which is the
 * restoration the person actually wanted — and it is why a terminal is created
 * on window load at all, which is what made the old contributed profile lose
 * its race.
 *
 * Only the tasks and automation shells are left alone: they ask for a shell to
 * run one command in and throw away, which is `terminal.integrated.
 * automationProfile.osx` and is nothing this launcher answers.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { shellQuote } from "../cli/install.js";

/** The launcher's file name, next to the control socket it talks to. */
export const TERMINAL_LAUNCHER_NAME = "devhub-terminal";

export interface TerminalLauncherRequest {
	/** The binary the launcher execs — the app's own Electron. */
	readonly execPath: string;
	/** The compiled entry point that binary runs as Node. */
	readonly entryScript: string;
	/** The control socket of the DevHub this launcher belongs to. */
	readonly socketPath: string;
}

export function terminalLauncherScript(
	request: TerminalLauncherRequest,
): string {
	return [
		"#!/bin/sh",
		"# Generated by DevHub on startup — do not edit, and do not copy.",
		"#",
		"# The three paths below name one running DevHub. They are rewritten every",
		"# time it starts, which is why moving or updating the app needs nothing",
		"# done to this file, and why a copy of it is a launcher for a DevHub that",
		"# may no longer be there.",
		`DEVHUB_CONTROL_SOCKET=${shellQuote(request.socketPath)} \\`,
		"ELECTRON_RUN_AS_NODE=1 \\",
		`exec ${shellQuote(request.execPath)} ${shellQuote(request.entryScript)} "$@"`,
		"",
	].join("\n");
}

/**
 * Write the launcher and return its path, for the profile that names it.
 *
 * Nothing is caught: a DevHub that cannot write its own launcher has no
 * terminals, and starting anyway would leave every terminal falling back to
 * whatever VS Code picks — which is the silent failure this file exists to end.
 */
export function installTerminalLauncher(
	launcherPath: string,
	request: TerminalLauncherRequest,
): string {
	mkdirSync(dirname(launcherPath), { recursive: true });
	writeFileSync(launcherPath, terminalLauncherScript(request), { mode: 0o755 });
	return launcherPath;
}

/** Where the launcher lives, given the user-data directory. */
export function terminalLauncherPath(userDataPath: string): string {
	return join(userDataPath, "devhub", TERMINAL_LAUNCHER_NAME);
}

/**
 * Which DevHub session this terminal belongs to, from the launcher's argv.
 *
 * The profile passes `${workspaceFolder}`, and VS Code resolves it in
 * `terminalProfileResolverService.ts#_resolveProfile` — but only when the
 * window has a folder. In the folderless window the resolver throws inside
 * `_resolveVariables`, which logs and returns the string untouched, so the
 * literal `${workspaceFolder}` arrives here. That is not an error to report:
 * the folderless window is DevHub's Scratch context, and `null` is its root.
 *
 * Anything that is not an absolute path is the same case. A relative path is
 * not something DevHub can name a session from, and guessing what it was
 * relative to would be inventing an answer.
 */
export function terminalRoot(argument: string | undefined): string | null {
	if (argument === undefined || !argument.startsWith("/")) return null;
	return argument;
}
