/**
 * The executable VS Code spawns for a DevHub terminal.
 *
 * DevHub's terminals live in a tmux server DevHub owns, and the argv that
 * attaches to one is DevHub's to compute — the session name, the socket and
 * the marker protocol belong to the terminal runtime and must not be spelled
 * anywhere else. So the integrated terminal does not run a shell: it runs this
 * launcher, which asks DevHub over the control socket (the `terminal-profile`
 * request) and `exec`s the answer.
 *
 * `exec` is the whole of how a tmux client's lifetime is tied to its terminal.
 * VS Code hangs up the pty when the terminal goes away, and a hangup reaches
 * the process the pty is holding — so that process must be tmux itself. The
 * asking runs as a child that has already exited by then (see
 * `devhubTerminal.ts`), leaving nothing between the pty and the client. Anything
 * left in between would make "the client dies with its terminal" depend on that
 * process passing a signal along, and a client that survives its terminal is one
 * nobody can see, close, or count.
 *
 * Why a file on disk rather than an extension-contributed profile. A
 * contributed profile is only a profile once the extension host has registered
 * the manifest *and* `TerminalProfileService` has refreshed its contributed
 * list — a throttled refresh that does a pty-host round trip first. A terminal
 * created on window load (the panel is visible, there are no persistent
 * sessions to restore, so `TerminalViewPane` creates one immediately) happens
 * before all of that and silently gets the OS shell: a plain zsh outside tmux.
 * A profile whose `path` is a real executable has no such window: it is a path
 * VS Code can spawn the moment it is asked.
 *
 * Why the script is *generated* on every startup, like the `devhub` CLI's
 * launcher in `../cli/install.ts`: it records the two absolute facts a launcher
 * cannot discover on its own — which binary runs it as Node (the app's own
 * Electron, since a system Node is exactly the thing in doubt) and which
 * control socket this DevHub is listening on. Regenerating means a moved or
 * updated app is never running yesterday's paths, and a second DevHub on
 * another profile never talks to the first one's socket.
 *
 * The socket is written *into* the script rather than read from the
 * environment because `DEVHUB_*` is a family a terminal is not supposed to
 * inherit — see `../shell/loginEnvironment.ts`.
 *
 * Who names this file to VS Code is the other half, and it is not a setting.
 * It was one — `terminal.integrated.profiles.osx` and the default that named
 * it, written into `User/settings.json` — and a settings file is the person's:
 * a dotfiles tool rewrote it wholesale, the keys went with it, and the next
 * reload was a plain zsh again. So the path goes into DevHub's own environment
 * as `DEVHUB_TERMINAL` (`exportTerminalLauncher`), and the patched
 * `TerminalProfileService` reads it and *is* the default, reading no terminal
 * setting at all. See `patches/vscode/0003-devhub-terminal-is-the-terminal.
 * patch`; `terminal.integrated.enablePersistentSessions` is forced off in the
 * same patch and for the same reason — a tmux session outlives the window
 * already, so a restored tab is a second, empty client for a session that is
 * still running.
 *
 * Only the tasks and automation shells are left alone: they ask for a shell to
 * run one command in and throw away, which is `terminal.integrated.
 * automationProfile.osx` and is nothing this launcher answers.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { shellQuote, shellQuoteArgv } from "../runtime/quote.js";

/** The launcher's file name, next to the control socket it talks to. */
export const TERMINAL_LAUNCHER_NAME = "devhub-terminal";

export interface TerminalLauncherRequest {
	/** The binary the launcher execs — the app's own Electron. */
	readonly execPath: string;
	/** The compiled entry point that binary runs as Node. */
	readonly entryScript: string;
	/** The control socket of the DevHub this launcher belongs to. */
	readonly socketPath: string;
}

export function terminalLauncherScript(
	request: TerminalLauncherRequest,
): string {
	return [
		"#!/bin/sh",
		"# Generated by DevHub on startup — do not edit, and do not copy.",
		"#",
		"# The three paths below name one running DevHub. They are rewritten every",
		"# time it starts, which is why moving or updating the app needs nothing",
		"# done to this file, and why a copy of it is a launcher for a DevHub that",
		"# may no longer be there.",
		"#",
		"# Ask DevHub for the argv, then *become* it. The asking is a child, so",
		"# that Node exits before tmux starts, and what VS Code's pty holds is the",
		"# tmux client itself — the process a hangup has to reach. A tmux client",
		"# that ran as a grandchild would outlive the pty whenever the process in",
		"# between failed to pass the hangup on, and a client that outlives the",
		"# terminal showing it is a client nobody can see or close.",
		`devhub_argv=$(DEVHUB_CONTROL_SOCKET=${shellQuote(request.socketPath)} \\`,
		"ELECTRON_RUN_AS_NODE=1 \\",
		`${shellQuote(request.execPath)} ${shellQuote(request.entryScript)} "$@") || exit $?`,
		"# An empty answer with a zero status is not an answer. Without this the",
		"# `exec` below would have no arguments, and a shell that execs nothing",
		"# carries on reading its input — which is a bare shell on the pty, the",
		"# one outcome this launcher exists to make impossible.",
		'if [ -z "$devhub_argv" ]; then',
		'\techo "devhub-terminal: DevHub answered without a command line." >&2',
		"\texit 1",
		"fi",
		'eval "exec $devhub_argv"',
		"",
	].join("\n");
}

/**
 * One shell word per argument, for the launcher to `exec`.
 *
 * The quoting is the launcher's own — `shellQuote` is what wrote the paths
 * into the script above — so the argv crosses the one gap between DevHub and
 * `/bin/sh` in the language the receiving side actually parses. Nothing here
 * ever sees a word split on a space in a path.
 */
export function terminalCommandLine(command: {
	readonly file: string;
	readonly args: readonly string[];
}): string {
	return shellQuoteArgv([command.file, ...command.args]);
}

/**
 * Write the launcher and return its path, for the profile that names it.
 *
 * Nothing is caught: a DevHub that cannot write its own launcher has no
 * terminals, and starting anyway would leave every terminal falling back to
 * whatever VS Code picks — which is the silent failure this file exists to end.
 */
export function installTerminalLauncher(
	launcherPath: string,
	request: TerminalLauncherRequest,
): string {
	mkdirSync(dirname(launcherPath), { recursive: true });
	writeFileSync(launcherPath, terminalLauncherScript(request), { mode: 0o755 });
	return launcherPath;
}

/** Where the launcher lives, given the user-data directory. */
export function terminalLauncherPath(userDataPath: string): string {
	return join(userDataPath, "devhub", TERMINAL_LAUNCHER_NAME);
}

/**
 * The directory a terminal belongs to, from what the launcher was started in.
 *
 * The profile carries no arguments and nothing is resolved into it. VS Code
 * spawns the terminal in the cwd it computed for it — the workspace folder when
 * the window has one, the user's home when it does not
 * (`terminalEnvironment.ts#getCwd`) — so the launcher simply asks where it is,
 * and DevHub answers which of its sessions that directory is in.
 *
 * A cwd is always absolute; anything that is not is a runtime that could not
 * say where it was, and `null` — the Scratch context — is the honest answer to
 * that rather than a guess.
 */
export function terminalRoot(directory: string | undefined): string | null {
	if (directory === undefined || !directory.startsWith("/")) return null;
	return directory;
}

/**
 * Which of these workspace roots contains `directory`, if any.
 *
 * One rule, and the same one for every window: a terminal belongs to the
 * workspace its directory is in, and to Scratch when no workspace contains it.
 * The folderless window is not a case of its own — VS Code starts its terminal
 * in the user's home, no workspace is rooted there, and Scratch is what falls
 * out of the rule.
 *
 * The longest match wins, so a workspace nested inside another one gets its own
 * terminals rather than its parent's. Matching is on whole path segments: a
 * root of `/work/app` does not contain `/work/app-old`.
 */
export function enclosingRoot(
	roots: readonly string[],
	directory: string | null,
): string | null {
	if (directory === null) return null;
	let best: string | null = null;
	for (const root of roots) {
		if (directory !== root && !directory.startsWith(`${root}/`)) continue;
		if (best === null || root.length > best.length) best = root;
	}
	return best;
}
