use std::fmt;

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::{DomainError, DomainErrorCode};

/// Native application lifecycle readiness owned by the coordinator. This is
/// not a provider status and does not create a second shell state store.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "lowercase")]
pub enum AppReadiness {
    Starting,
    Ready,
    Unavailable,
}

macro_rules! operation_id {
    ($name:ident) => {
        #[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub struct $name(String);

        impl $name {
            pub fn from_uuid(raw: impl Into<String>) -> Result<Self, DomainError> {
                let raw = raw.into();
                if !is_canonical_uuid(&raw) {
                    return Err(DomainError::new(DomainErrorCode::InvalidId));
                }
                Ok(Self(raw))
            }

            #[cfg(test)]
            pub fn for_test(raw: impl Into<String>) -> Self {
                Self::from_uuid(raw).expect("test operation identity must be canonical UUID")
            }

            pub fn as_str(&self) -> &str {
                &self.0
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
                formatter.write_str(&self.0)
            }
        }
    };
}

fn is_canonical_uuid(raw: &str) -> bool {
    raw.len() == 36
        && raw == raw.to_ascii_lowercase()
        && raw.bytes().enumerate().all(|(index, byte)| {
            if matches!(index, 8 | 13 | 18 | 23) {
                byte == b'-'
            } else {
                byte.is_ascii_hexdigit()
            }
        })
}

// Generated by the trusted shell/Bridge ingress and used as the correlation
// root for one user operation through every coordinator generation.
operation_id!(IntentId);
operation_id!(OperationId);
operation_id!(ConfirmationId);
operation_id!(ProviderEventId);

impl From<OperationId> for ProviderEventId {
    fn from(operation_id: OperationId) -> Self {
        Self::from_uuid(operation_id.as_str().to_owned())
            .expect("an OperationId is always a canonical ProviderEventId")
    }
}

/// A completion is accepted only for the exact operation generation that
/// created it.  This prevents a late provider event from mutating a newer
/// operation for the same domain identity.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct OperationToken {
    operation_id: OperationId,
    generation: u64,
}

impl OperationToken {
    pub const fn new(operation_id: OperationId, generation: u64) -> Self {
        Self { operation_id, generation }
    }

    pub fn operation_id(&self) -> &OperationId {
        &self.operation_id
    }

    pub const fn generation(&self) -> u64 {
        self.generation
    }
}
