/**
 * Putting `devhub` on the PATH.
 *
 * VS Code installs `code` by dropping a small shell script into a directory
 * that is already on the PATH; this does the same thing for the same reason.
 * The script is *generated* rather than symlinked because it is the one place
 * the two absolute facts a CLI cannot discover on its own are recorded: which
 * binary to run it with, and which socket the app it belongs to is listening
 * on. A symlink would make the CLI guess both, and a guess that is usually
 * right is the worst kind.
 *
 * Consequence, and it is stated in the script itself: moving or reinstalling
 * DevHub invalidates the launcher, and the command has to be run again.
 *
 * `sudo` is never used, and never offered. If `/usr/local/bin` is not writable
 * the launcher goes to `~/.local/bin` and the person is told, in the same
 * sentence, what to add to their PATH if it is not there already. Silently
 * escalating to root to write a file into a system directory is not something
 * a menu command gets to do.
 */

import { accessSync, constants, mkdirSync, writeFileSync } from "node:fs";
import { delimiter, join } from "node:path";

export interface InstallRequest {
	/** The binary the launcher execs — the app's own Electron. */
	readonly execPath: string;
	/** The compiled CLI script that binary runs as Node. */
	readonly cliScript: string;
	/** The control socket of the app doing the installing. */
	readonly socketPath: string;
	/**
	 * What the launcher is called, and which DevHub it belongs to.
	 *
	 * A profile installs its own command — `devhub` for the default one,
	 * `devhub-dev` for a development profile — so a second DevHub does not
	 * quietly take the first one's name in the PATH. The profile travels in the
	 * script as well, because the CLI needs it to know which bundle to ask
	 * macOS for when nothing is listening.
	 */
	readonly commandName: string;
	readonly profile: string;
	readonly home: string;
	/** The PATH the installing process sees, for the "add this" advice. */
	readonly pathValue: string;
	/** Overridden by the tests; production uses the two real candidates. */
	readonly candidates?: readonly string[];
}

export interface InstallResult {
	readonly launcherPath: string;
	readonly message: string;
}

/** In order of preference: the shared one first, then the per-user one. */
export function defaultCandidates(home: string): readonly string[] {
	return ["/usr/local/bin", join(home, ".local", "bin")];
}

/** Quote a path for a POSIX shell, whatever is in it. */
export function shellQuote(value: string): string {
	return `'${value.replaceAll("'", `'\\''`)}'`;
}

export function launcherScript(request: InstallRequest): string {
	return [
		"#!/bin/sh",
		"# Generated by DevHub — do not edit.",
		"#",
		"# Run the workbench command \"DevHub: Install 'devhub' command in PATH\"",
		"# again after moving, updating or reinstalling DevHub: the three paths",
		"# below are absolute, and that is what makes this script work without a",
		"# system Node installation.",
		`DEVHUB_CONTROL_SOCKET=${shellQuote(request.socketPath)} \\`,
		`DEVHUB_PROFILE=${shellQuote(request.profile)} \\`,
		"ELECTRON_RUN_AS_NODE=1 \\",
		`exec ${shellQuote(request.execPath)} ${shellQuote(request.cliScript)} "$@"`,
		"",
	].join("\n");
}

function isWritableDirectory(path: string): boolean {
	try {
		accessSync(path, constants.W_OK | constants.X_OK);
		return true;
	} catch {
		// Not a fallback that hides a failure: this is the question being
		// asked. An unwritable /usr/local/bin is the ordinary case on a Mac
		// with no Homebrew, and the answer is the next candidate.
		return false;
	}
}

function onPath(directory: string, pathValue: string): boolean {
	return pathValue.split(delimiter).includes(directory);
}

/**
 * Write the launcher into the first candidate directory that will take it.
 *
 * Throws if none will. A command that reported success while having installed
 * nothing is exactly the silent lie this codebase does not permit.
 */
export function installLauncher(request: InstallRequest): InstallResult {
	const candidates = request.candidates ?? defaultCandidates(request.home);
	const refused: string[] = [];
	for (const directory of candidates) {
		if (!isWritableDirectory(directory)) {
			// The per-user directory is ours to create; a system one is not.
			if (directory.startsWith(`${request.home}/`)) {
				mkdirSync(directory, { recursive: true, mode: 0o755 });
			} else {
				refused.push(directory);
				continue;
			}
		}
		const launcherPath = join(directory, request.commandName);
		writeFileSync(launcherPath, launcherScript(request), { mode: 0o755 });
		return {
			launcherPath,
			message: installMessage(directory, launcherPath, refused, request),
		};
	}
	throw new Error(
		`none of these directories would take the launcher: ${candidates.join(", ")}`,
	);
}

function installMessage(
	directory: string,
	launcherPath: string,
	refused: readonly string[],
	request: InstallRequest,
): string {
	const parts = [
		`Installed the '${request.commandName}' command at ${launcherPath}.`,
	];
	if (refused.length > 0) {
		parts.push(
			`${refused.join(" and ")} ${refused.length === 1 ? "is" : "are"} not writable, so it was not used — DevHub does not use sudo.`,
		);
	}
	if (!onPath(directory, request.pathValue)) {
		parts.push(
			`${directory} is not on your PATH. Add it, for example with: export PATH="${directory}:$PATH"`,
		);
	}
	return parts.join(" ");
}
